[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:redis]
priority=10
command=/usr/bin/redis-server --port 6379 --requirepass giang --bind 127.0.0.1 --save "" --appendonly no
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:api]
priority=20
command=/app/server
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=PORT="8000",REDIS_HOST="127.0.0.1",REDIS_PORT="6379",REDIS_PASSWORD="giang",PUBLIC_APP_URL="%(ENV_PUBLIC_APP_URL)s",NODE_ENV="production"

[program:web]
priority=30
command=bun apps/web/server.js
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=PORT="3001",HOSTNAME="127.0.0.1",NODE_ENV="production",VKARA_AIO="1"

[program:caddy]
priority=40
command=caddy run --config /app/Caddyfile --adapter caddyfile
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
