'use client';

import React, { createContext, useContext, useEffect, useRef, useCallback, useMemo } from 'react';
import { usePathname, useSearchParams } from 'next/navigation';

import { isValidRoomId, resolveWebSocketEndpoint } from '@vkara/room';

import { env } from '@/env';
import { ErrorCode } from '@vkara/room';
import type { WebSocketState } from '@/types/websocket.type';
import { parseUrlCommands } from '@vkara/url-commands';

import { getEffectiveLayoutMode } from '@/lib/layout-mode';
import { isDedicatedTvRoute } from '@/lib/tv-route';
import { setUserDisplayName } from '@/lib/device-label';
import { useUrlCommandStore } from '@/store/urlCommandStore';
import { captureTvRoomSnapshot, recoverTvRoom } from '@/lib/tv-room-recovery';
import { useIsRoomSessionReady } from '@/hooks/use-room-session-ready';
import { useViewportWidth } from '@/hooks/use-viewport-layout';
import { useYouTubeStore } from '@/store/youtubeStore';
import { useWebSocketStore, initializeWebSocket } from '@/store/websocketStore';
import {
    ensureDeviceLabelResolved,
    getUserDisplayName,
    isAutoGeneratedDisplayName,
} from '@/lib/device-label';
import { getOrCreateDeviceId } from '@/lib/device-id';
import { selectRejoinPassword, useRoomRejoinSecretStore } from '@/store/roomRejoinSecretStore';
import { isFatalRejoinError } from '@/lib/room-session-lifecycle';

interface EnhancedWebSocketState extends WebSocketState {
    ensureConnectedAndSend: WebSocketState['sendMessage'];
    isRoomSessionReady: boolean;
}

const WebSocketContext = createContext<EnhancedWebSocketState | undefined>(undefined);

function getWebSocketUrl(): string {
    const wsEnv = env.NEXT_PUBLIC_WS_URL?.trim();
    if (wsEnv) {
        return resolveWebSocketEndpoint(wsEnv);
    }

    const apiEnv = env.NEXT_PUBLIC_API_URL?.trim();
    if (apiEnv?.startsWith('/')) {
        const protocol = window.location.protocol === 'https:' ? 'wss' : 'ws';
        return `${protocol}://${window.location.host}/ws`;
    }

    return resolveWebSocketEndpoint('ws://localhost:8000');
}

export const useWebSocket = (): EnhancedWebSocketState => {
    const context = useContext(WebSocketContext);
    if (context === undefined) {
        throw new Error('useWebSocket must be used within a WebSocketProvider');
    }
    return context;
};

export const WebSocketProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const pathname = usePathname();
    const searchParams = useSearchParams();
    const connectionStatus = useWebSocketStore((s) => s.connectionStatus);
    const connectionEpoch = useWebSocketStore((s) => s.connectionEpoch);
    const roomSessionEpoch = useWebSocketStore((s) => s.roomSessionEpoch);
    const sendMessage = useWebSocketStore((s) => s.sendMessage);
    const connect = useWebSocketStore((s) => s.connect);
    const disconnect = useWebSocketStore((s) => s.disconnect);
    const forceReconnect = useWebSocketStore((s) => s.forceReconnect);
    const clearRoomScopedMessages = useWebSocketStore((s) => s.clearRoomScopedMessages);
    const clearPendingMessages = useWebSocketStore((s) => s.clearPendingMessages);
    const isMessagePending = useWebSocketStore((s) => s.isMessagePending);
    const getPendingMessages = useWebSocketStore((s) => s.getPendingMessages);

    const roomId = useYouTubeStore((s) => s.room?.id);
    const legacyRoomPassword = useYouTubeStore((s) => s.room?.password);
    const storedRejoinPassword = useRoomRejoinSecretStore(selectRejoinPassword(roomId));
    const rejoinPassword = storedRejoinPassword ?? legacyRoomPassword;
    const layoutMode = useYouTubeStore((s) => s.layoutMode);
    const layoutModeSource = useYouTubeStore((s) => s.layoutModeSource);
    const tvSuppressAutoCreate = useYouTubeStore((s) => s.tvSuppressAutoCreate);
    const setRoom = useYouTubeStore((s) => s.setRoom);
    const enterTvLobby = useYouTubeStore((s) => s.enterTvLobby);
    const viewportWidth = useViewportWidth();

    const wsInitialized = useRef(false);
    const lastSyncedEpoch = useRef(-1);
    const recoveryInFlight = useRef(false);
    const abandonedRoomIdRef = useRef<string | null>(null);
    const connectionEpochRef = useRef(connectionEpoch);
    const isTvLayoutRef = useRef(false);
    const roomIdRef = useRef(roomId);
    const rejoinPasswordRef = useRef(rejoinPassword);
    const ensureConnectedAndSendRef = useRef<WebSocketState['sendMessage']>(() => {});
    const beginTvRecoveryRef = useRef<
        (snapshotRoom?: ReturnType<typeof useYouTubeStore.getState>['room']) => boolean
    >(() => false);
    const setRoomRef = useRef(setRoom);
    const enterTvLobbyRef = useRef(enterTvLobby);
    connectionEpochRef.current = connectionEpoch;
    roomIdRef.current = roomId;
    rejoinPasswordRef.current = rejoinPassword;
    setRoomRef.current = setRoom;
    enterTvLobbyRef.current = enterTvLobby;

    const parsedCommand = parseUrlCommands(searchParams.toString());
    if (parsedCommand.document.name) {
        setUserDisplayName(parsedCommand.document.name);
    }
    useUrlCommandStore.getState().setSnapshot(parsedCommand);
    const snapshotDocument =
        useUrlCommandStore.getState().snapshot?.document ?? parsedCommand.document;
    const roomIdParam = snapshotDocument.roomId;
    const passwordParam = snapshotDocument.password;
    const joinTokenParam = snapshotDocument.joinToken;
    const hasInviteInUrl = Boolean(roomIdParam && isValidRoomId(roomIdParam));

    const effectiveLayoutMode = getEffectiveLayoutMode({
        storedLayoutMode: layoutMode,
        layoutModeSource,
        viewportWidth,
    });

    const isDedicatedTv = isDedicatedTvRoute(pathname);
    const isTvLayout = isDedicatedTv || effectiveLayoutMode !== 'remote';
    isTvLayoutRef.current = isTvLayout;

    const isRoomSessionReady = useIsRoomSessionReady();

    const ensureConnectedAndSend: WebSocketState['sendMessage'] = useCallback(
        (messageData) => {
            if (connectionStatus !== 'OPEN') {
                connect();
            }
            return sendMessage(messageData);
        },
        [connectionStatus, connect, sendMessage],
    );
    ensureConnectedAndSendRef.current = ensureConnectedAndSend;

    const beginTvRecovery = useCallback(
        (snapshotRoom = useYouTubeStore.getState().room) => {
            if (!isTvLayout || recoveryInFlight.current) return false;

            recoveryInFlight.current = true;
            const snapshot = captureTvRoomSnapshot(snapshotRoom);
            if (snapshot) {
                abandonedRoomIdRef.current = snapshot.previousRoomId;
            }

            lastSyncedEpoch.current = -1;
            clearRoomScopedMessages();
            recoverTvRoom(ensureConnectedAndSend, snapshot);
            return true;
        },
        [isTvLayout, clearRoomScopedMessages, ensureConnectedAndSend],
    );
    beginTvRecoveryRef.current = beginTvRecovery;

    // Lifecycle side-effects via store subscription — do not subscribe to lastMessage in React
    // render, or every inbound message re-renders the provider and all useWebSocket() consumers.
    useEffect(() => {
        let prevLastMessage = useWebSocketStore.getState().lastMessage;
        return useWebSocketStore.subscribe((state) => {
            if (state.lastMessage === prevLastMessage) {
                return;
            }
            prevLastMessage = state.lastMessage;
            const lastMessage = state.lastMessage;
            if (!lastMessage) {
                return;
            }

            if (lastMessage.type === 'roomJoined' || lastMessage.type === 'roomCreated') {
                recoveryInFlight.current = false;
                abandonedRoomIdRef.current = null;
                useWebSocketStore.setState({
                    roomSessionEpoch: connectionEpochRef.current,
                });
                return;
            }

            const tvLayout = isTvLayoutRef.current;
            const activeRoomId = roomIdRef.current;

            if (lastMessage.type === 'roomClosed' || lastMessage.type === 'kicked') {
                lastSyncedEpoch.current = -1;
                if (tvLayout) {
                    enterTvLobbyRef.current();
                } else {
                    setRoomRef.current(null);
                }
                return;
            }

            if (
                lastMessage.type === 'errorWithCode' &&
                lastMessage.code === ErrorCode.NOT_IN_ROOM
            ) {
                if (!activeRoomId || recoveryInFlight.current) {
                    return;
                }
                if (abandonedRoomIdRef.current === activeRoomId) {
                    return;
                }

                lastSyncedEpoch.current = -1;
                ensureConnectedAndSendRef.current({
                    type: 'reJoinRoom',
                    roomId: activeRoomId,
                    password: rejoinPasswordRef.current,
                    isTvClient: tvLayout,
                });
                return;
            }

            if (
                lastMessage.type === 'errorWithCode' &&
                lastMessage.code === ErrorCode.REJOIN_ROOM_NOT_FOUND
            ) {
                if (activeRoomId) {
                    abandonedRoomIdRef.current = activeRoomId;
                }
                lastSyncedEpoch.current = -1;
                if (tvLayout) {
                    beginTvRecoveryRef.current(useYouTubeStore.getState().room);
                }
                return;
            }

            if (lastMessage.type === 'errorWithCode' && isFatalRejoinError(lastMessage.code)) {
                if (activeRoomId) {
                    abandonedRoomIdRef.current = activeRoomId;
                }
                lastSyncedEpoch.current = -1;
                if (tvLayout) {
                    enterTvLobbyRef.current();
                }
                return;
            }

            if (lastMessage.type === 'roomNotFound') {
                if (activeRoomId) {
                    abandonedRoomIdRef.current = activeRoomId;
                }
                lastSyncedEpoch.current = -1;
                if (tvLayout) {
                    enterTvLobbyRef.current();
                }
            }
        });
    }, []);

    const hadInviteRef = useRef(false);
    useEffect(() => {
        const inviteAppeared = hasInviteInUrl && !hadInviteRef.current;
        hadInviteRef.current = hasInviteInUrl;
        if (inviteAppeared) {
            lastSyncedEpoch.current = -1;
        }
    }, [hasInviteInUrl]);

    useEffect(() => {
        lastSyncedEpoch.current = -1;
    }, [effectiveLayoutMode]);

    useEffect(() => {
        if (wsInitialized.current) return;

        wsInitialized.current = true;
        const cleanup = initializeWebSocket({
            url: getWebSocketUrl(),
            reconnectAttempts: Infinity,
            initialRetryDelay: 800,
            maxRetryDelay: 20000,
            heartbeatInterval: 25000,
            heartbeatTimeout: 8000,
            messageTimeout: 8000,
        });

        return cleanup;
    }, []);

    // Warm Client Hints / UA label cache before join/create (async model on Android Chrome).
    // If we already joined with a coarse fallback ("Android"), upgrade once the model resolves.
    useEffect(() => {
        let cancelled = false;
        void (async () => {
            const label = await ensureDeviceLabelResolved({ isTvClient: isTvLayout });
            if (cancelled || getUserDisplayName()) return;

            const room = useYouTubeStore.getState().room;
            const deviceId = getOrCreateDeviceId();
            if (!room?.id || !deviceId) return;

            const me = room.participants?.[deviceId];
            if (!me || me.displayName === label) return;
            // Only replace auto-generated placeholders, never a name the user typed in-room.
            if (!isAutoGeneratedDisplayName(me.displayName)) return;

            ensureConnectedAndSend({ type: 'setDisplayName', displayName: label });
        })();
        return () => {
            cancelled = true;
        };
    }, [isTvLayout, roomId, ensureConnectedAndSend]);

    const syncRoomSession = useCallback(() => {
        if (connectionStatus !== 'OPEN') return;
        if (lastSyncedEpoch.current === connectionEpoch) return;
        if (recoveryInFlight.current) return;
        lastSyncedEpoch.current = connectionEpoch;

        if (hasInviteInUrl && roomIdParam) {
            ensureConnectedAndSend({
                type: 'joinRoom',
                roomId: roomIdParam,
                password: joinTokenParam ? undefined : passwordParam?.trim() || undefined,
                joinToken: joinTokenParam,
                isTvClient: isTvLayout,
            });
            return;
        }

        if (roomId) {
            ensureConnectedAndSend({
                type: 'reJoinRoom',
                roomId,
                password: rejoinPassword,
                isTvClient: isTvLayout,
            });
            return;
        }

        if (isTvLayout && !tvSuppressAutoCreate) {
            ensureConnectedAndSend({ type: 'createRoom', isTvClient: true });
        }
    }, [
        connectionStatus,
        connectionEpoch,
        hasInviteInUrl,
        roomIdParam,
        passwordParam,
        joinTokenParam,
        roomId,
        rejoinPassword,
        isTvLayout,
        tvSuppressAutoCreate,
        ensureConnectedAndSend,
    ]);

    const wakeConnection = useCallback(() => {
        if (document.visibilityState !== 'visible') return;

        lastSyncedEpoch.current = -1;

        if (connectionStatus === 'OPEN') {
            syncRoomSession();
            return;
        }

        forceReconnect();
    }, [connectionStatus, forceReconnect, syncRoomSession]);

    useEffect(() => {
        const onVisible = () => {
            if (document.visibilityState === 'visible') {
                wakeConnection();
            }
        };
        const onOnline = () => wakeConnection();
        const onPageShow = (event: PageTransitionEvent) => {
            if (event.persisted) {
                wakeConnection();
            }
        };
        const onFocus = () => wakeConnection();

        document.addEventListener('visibilitychange', onVisible);
        window.addEventListener('online', onOnline);
        window.addEventListener('pageshow', onPageShow);
        window.addEventListener('focus', onFocus);

        return () => {
            document.removeEventListener('visibilitychange', onVisible);
            window.removeEventListener('online', onOnline);
            window.removeEventListener('pageshow', onPageShow);
            window.removeEventListener('focus', onFocus);
        };
    }, [wakeConnection]);

    useEffect(() => {
        syncRoomSession();
    }, [syncRoomSession]);

    useEffect(() => {
        if (!roomId) {
            lastSyncedEpoch.current = -1;
        }
    }, [roomId]);

    const enhancedWebSocketStore = useMemo<EnhancedWebSocketState>(
        () => ({
            sendMessage,
            connectionStatus,
            connectionEpoch,
            roomSessionEpoch,
            connect,
            disconnect,
            forceReconnect,
            isMessagePending,
            getPendingMessages,
            clearPendingMessages,
            clearRoomScopedMessages,
            ensureConnectedAndSend,
            isRoomSessionReady,
        }),
        [
            sendMessage,
            connectionStatus,
            connectionEpoch,
            roomSessionEpoch,
            connect,
            disconnect,
            forceReconnect,
            isMessagePending,
            getPendingMessages,
            clearPendingMessages,
            clearRoomScopedMessages,
            ensureConnectedAndSend,
            isRoomSessionReady,
        ],
    );

    return (
        <WebSocketContext.Provider value={enhancedWebSocketStore}>
            {children}
        </WebSocketContext.Provider>
    );
};
