name: Build and push Docker images

on:
    push:
        branches:
            - main
            - develop
        tags:
            - 'v*'
    workflow_dispatch:

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    check-skip:
        runs-on: ubuntu-latest
        outputs:
            skip_docker: ${{ steps.check_skip_docker.outputs.skip_docker }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Check if commit message contains [skip docker]
              id: check_skip_docker
              run: |
                  commit_message=$(git log -1 --pretty=%B)
                  if [[ "$commit_message" == *"[skip docker]"* ]]; then
                    echo "skip_docker=true" >> $GITHUB_OUTPUT
                    echo "Skip Docker build and push found in commit message."
                  else
                    echo "skip_docker=false" >> $GITHUB_OUTPUT
                  fi

    build:
        needs: [check-skip]
        if: ${{ needs.check-skip.outputs.skip_docker != 'true' }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                app:
                    - name: api
                      image: lehuygiang28/vkara-api
                      dockerfile: ./apps/api/Dockerfile
                    - name: web
                      image: lehuygiang28/vkara-web
                      dockerfile: ./apps/web/Dockerfile
                    - name: api-redis-bundle
                      image: lehuygiang28/vkara-api-redis
                      dockerfile: ./apps/api/containers/redis-bundle/Dockerfile
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v6
              with:
                  images: ${{ matrix.app.image }}
                  tags: |
                      type=sha,format=short
                      type=raw,value=latest,enable={{is_default_branch}}
                      type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}
                      type=ref,event=tag

            - name: Build and push ${{ matrix.app.name }} image
              uses: docker/build-push-action@v7
              with:
                  context: .
                  file: ${{ matrix.app.dockerfile }}
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
